name: Sync AWAvenue Rule

on:
  schedule:
    - cron: '0 2 * * *' # 每天 UTC 时间 2 点（北京时间 10 点）自动运行
  workflow_dispatch: # 允许你在 Actions 页面手动点击运行

jobs:
  update-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予推送到仓库的权限
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Rule File
        run: |
          # 创建存放文件的文件夹（如果你想放在根目录，可以删除 mkdir 这行，并修改下方 -o 的路径）
          mkdir -p Filters
          curl -sL https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Singbox.json -o Filters/AWAvenue-Ads-Rule-Singbox.json

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Filters/AWAvenue-Ads-Rule-Singbox.json
          # 如果文件没有变化，则不提交
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update AWAvenue-Ads-Rule-Singbox.json" && git push)

