name: Convert AdGuard Rules to sing-box SRS

on:
  push:
    paths:
      - 'agh_rules_clean.txt'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: sudo apt-get update && sudo apt-get install -y jq curl wget

      - name: 获取并安装最新版 sing-box
        run: |
          set -e

          VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          echo "Latest sing-box version: $VERSION"

          FILE="sing-box-${VERSION#v}-linux-amd64.tar.gz"

          wget -q "https://github.com/SagerNet/sing-box/releases/download/${VERSION}/${FILE}"

          tar -xzf "$FILE"

          sudo cp sing-box-*/sing-box /usr/local/bin/

          sing-box version

      - name: 转换 AdGuard 规则为 SRS
        run: |
          set -e

          rm -f agh_rules_clean.srs

          sing-box rule-set convert \
            --type adguard \
            --output agh_rules_clean.srs \
            agh_rules_clean.txt

      - name: 提交并推送
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add agh_rules_clean.srs

          if ! git diff --cached --quiet; then
            git commit -m "Auto update SRS rules [skip ci]"
            git push
          else
            echo "No changes, skip commit"
          fi
